development: &default
  bucket: jmission-jo-dev
  host: jmission-jo-dev.s3.amazonaws.com
  protocol: https

test:
  bucket: jmission-jo-dev
  host: jmission-jo-dev.s3.amazonaws.com
  protocol: https

production:
  bucket: jmission-jo
  host: jmission-jo.s3.amazonaws.com
  protocol: https

staging:
  bucket: jmission-jo-stg
  host: jmission-jo-stg.s3.amazonaws.com
  protocol: https
